'use client';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, Volume2, VolumeX, Expand, Code2, BriefcaseBusiness, Mail } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const experience = [
{role:'Backend Developer Mid',company:'CASTraining',client:'Proyecto vinculado a IBM / Viewnext · Banco Santander',date:'AGO 2026 — ACTUALIDAD',body:['Incorporación a un programa de modernización de una plataforma bancaria, orientado a la evolución de arquitectura on-premise hacia AWS.','Desarrollo de microservicios backend, APIs, mensajería asíncrona, testing automatizado y revisión de código.'],stack:'Entorno previsto: Java 17+ / 21, Spring Boot 3, Kafka, arquitectura hexagonal y API First / OpenAPI.'},
{role:'Backend Java Developer',company:'Azertium IT Global Services',client:'PhoneHouse · E-commerce',date:'DIC 2025 — AGO 2026',body:['Microservicios con Java 21, Spring Boot y Maven para flujos e-commerce. APIs REST y contratos internos con OpenAPI / Swagger.','Integración con VTEX OMS, webhooks y servicios internos. Procesamiento asíncrono de eventos con AWS SQS FIFO.','PostgreSQL / Amazon RDS y migraciones con Flyway. Observabilidad con Datadog y calidad con SonarQube.','Trabajo en Scrum, GitFlow, CI/CD y revisión técnica de pull requests.'],stack:'Java 21 · Spring Boot · AWS SQS · PostgreSQL'},
{role:'Full Stack Developer',company:'TheWise Dreams',client:'Aplicaciones web',date:'SEP 2024 — NOV 2025',body:['Desarrollo de aplicaciones web con Java, Spring Boot, JavaScript y React.','Diseño e implementación de APIs REST y lógica backend orientada a negocio.','Modelado y gestión de bases de datos SQL. Git / GitHub para control de versiones y despliegue de proyectos.'],stack:'Java · Spring Boot · React · SQL'},
{role:'Desarrollador de Software en Prácticas',company:'Bet Solar',client:'Desarrollo de software',date:'SEP 2023 — JUL 2024',body:['Desarrollo y mantenimiento de funcionalidades backend y frontend, bases de datos, corrección de incidencias y control de versiones con Git.'],stack:'Backend · Frontend · Bases de datos · Git'},
];
const skills = [['Backend','Java 21, Spring Boot, REST APIs, Microservicios, OpenFeign, Hibernate, JPA, Spring Security, JWT, Keycloak, JSON'],['Cloud e integración','AWS, AWS SQS, Kafka, Spring Batch, OpenAPI / Swagger, VTEX, Webhooks'],['Bases de datos','PostgreSQL, Amazon RDS, Flyway, SQL'],['Calidad y testing','JUnit 5, Mockito, SonarQube, Datadog'],['Herramientas y DevOps','Git, Bitbucket, GitHub, GitFlow, Maven, Docker, Kubernetes, Terraform, Jenkins, CI/CD, Spec-Driven Development'],['Metodologías','Scrum']];
const sectionIds = ['perfil','experiencia','stack','formacion','idiomas','contacto'];
const sections = ['Perfil','Experiencia','Stack técnico','Formación','Idiomas','Contacto'];
const sectionHints = ['La persona detrás del código.', 'De las primeras líneas a banca y e-commerce.', 'Mi caja de herramientas backend.', 'La base de todo lo que construyo.', 'Madrid, Irlanda y conversaciones sin barreras.', 'El siguiente capítulo empieza hablando.'];
const links={github:'https://github.com/Cansynku',linkedin:'https://www.linkedin.com/in/javier-cano-garc%C3%ADa/',email:'mailto:jcanogarcia96@gmail.com'};
function Content({section}:{section:number}) {
if(section===0) return <><div className="profile-line"><Image src="/javier.jpg" alt="Javier Cano García" width={90} height={100} unoptimized/><div><span className="eyebrow">PLAYER 01</span><h2>Javier Cano<br/>García</h2></div></div><p className="role">Backend Developer · Java & Spring Boot</p><p>Desarrollador backend con más de 3 años de experiencia en desarrollo de software. Especializado en Java y Spring Boot, APIs REST, microservicios e integración de sistemas.</p><p>Experiencia en proyectos enterprise, metodologías ágiles y buenas prácticas de desarrollo.</p><div className="lcd-tags"><span>Madrid, España</span><span>Java 21</span><span>Spring Boot</span></div></>;
if(section===1) return <><h2>Experiencia</h2>{experience.map(e=><article className="job" key={e.company}><span className="eyebrow">{e.date}</span><h3>{e.role}</h3><strong>{e.company}</strong><p className="client">{e.client} · Madrid · Remoto</p><ul>{e.body.map(b=><li key={b}>{b}</li>)}</ul><p className="stack-note">{e.stack}</p></article>)}</>;
if(section===2) return <><h2>Stack técnico</h2><p>Herramientas y competencias recogidas en mi CV.</p>{skills.map(([title,list])=><article className="skill-group" key={title}><h3>{title}</h3><div className="lcd-tags">{list.split(', ').map(s=><span key={s}>{s}</span>)}</div></article>)}</>;
if(section===3) return <><span className="eyebrow">SEP 2022 — JUL 2024</span><h2>Desarrollo de Aplicaciones Multiplataforma</h2><h3>Grado Superior · Universidad Francisco de Vitoria</h3><p>Madrid, España</p><p>Formación en desarrollo de aplicaciones, bases de datos, programación orientada a objetos, seguridad, usabilidad y calidad del software.</p><div className="lcd-callout">Modalidad dual con 9 meses de prácticas en empresa real.</div></>;
if(section===4) return <><h2>Sin barreras de idioma.</h2><article className="job"><span className="eyebrow">ES</span><h3>Español</h3><p>Nativo.</p></article><article className="job"><span className="eyebrow">EN</span><h3>Inglés</h3><p>Nivel alto. Dos años viviendo y trabajando en Irlanda, con uso diario del idioma en entornos laborales y atención al público.</p></article></>;
return <><span className="eyebrow">CONTINUE?</span><h2>Hablemos.</h2><p>¿Un proyecto backend, una oportunidad o una conversación sobre tecnología?</p><div className="contact-list"><a href={links.email}>jcanogarcia96@gmail.com ↗</a><a href="tel:+34695721814">+34 695 721 814 ↗</a><a href={links.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href={links.github} target="_blank" rel="noreferrer">GitHub · Cansynku ↗</a></div><p>Madrid, España</p><a className="lcd-download" href="/Javier_Cano_CV_Backend_Java_2026.pdf" download>↓ Descargar CV en PDF</a></>;
}
export default function Home(){
const [selected,setSelected]=useState(0);const [section,setSection]=useState<number|null>(null);const [sound,setSound]=useState(false);const [reading,setReading]=useState(false);const screen=useRef<HTMLDivElement>(null);const audio=useRef<AudioContext|null>(null);const [boot,setBoot]=useState(0);const [visited,setVisited]=useState<number[]>([]);const [progress,setProgress]=useState(0);
function openSection(index:number){setSelected(index);setSection(index);setVisited(v=>v.includes(index)?v:[...v,index]);beep();}
function explore(index:number){openSection(index);document.getElementById('console')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});}
function sideways(delta:number){if(section===null)move(delta);else openSection((section+delta+sections.length)%sections.length);}
function beep(){if(!sound)return;try{const ctx=audio.current??new AudioContext();audio.current=ctx;void ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.type='square';o.frequency.value=440;g.gain.setValueAtTime(.018,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.07);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.08);}catch{}}
function move(delta:number){beep();if(section!==null)screen.current?.scrollBy({top:delta*130,behavior:'smooth'});else setSelected(v=>(v+delta+sections.length)%sections.length);}
function enter(){beep();if(section===null){openSection(selected);screen.current?.scrollTo(0,0);}}
function back(){beep();setSection(null);}
useEffect(()=>{const el=screen.current;if(!el)return;el.scrollTo(0,0);const update=()=>setProgress(el.scrollHeight<=el.clientHeight?100:Math.round(el.scrollTop/(el.scrollHeight-el.clientHeight)*100));update();el.addEventListener('scroll',update,{passive:true});const observer=new ResizeObserver(update);observer.observe(el);return()=>{el.removeEventListener('scroll',update);observer.disconnect();};},[section]);
useEffect(()=>{function key(e:KeyboardEvent){if(reading||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA/.test((e.target as HTMLElement).tagName)|| (e.key==="Enter" && /BUTTON|A/.test((e.target as HTMLElement).tagName)))return;if(['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Enter','Escape','a','b'].includes(e.key)){e.preventDefault();if(e.key==='ArrowDown')move(1);else if(e.key==='ArrowUp')move(-1);else if(e.key==='ArrowRight')sideways(1);else if(e.key==='ArrowLeft')sideways(-1);else if(e.key==='Escape'||e.key==='b')back();else enter();}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
return <div className="site"><a className="skip" href="#console">Ir a la consola</a><header className="topbar"><button className="wordmark" onClick={back} aria-label="Volver al inicio"><span className="logo">JC<span>_</span></span><span>JAVIER CANO<span className="wordmark-sub">BACKEND DEVELOPER</span></span></button><div className="header-actions"><span className="location">MADRID, ES <span className="green-dot"/></span><a className="download" href="/Javier_Cano_CV_Backend_Java_2026.pdf" download><ArrowDownToLine size={16}/> Descargar CV</a></div></header>
<main className="stage"><aside className="intro"><div className="edition"><span/> DEV BOY · EDICIÓN 2026</div><h1>Serio con<br/>el código.<br/><em>Con ganas<br/>de jugar.</em></h1><p>Soy Javier. Desarrollo sistemas backend con Java y Spring Boot.<br/>APIs, microservicios e integración de sistemas.<br/>A los mandos, tú.</p><div className="career-context"><span>E-COMMERCE</span><span>BANCA</span><span>JAVA 21</span></div><div className="intro-actions"><button className="primary-action" onClick={()=>explore(1)}>Explorar mi experiencia <ArrowUpRight size={17}/></button><a className="contact-action" href={links.email}>Hablemos <Mail size={16}/></a></div><button className="text-link" onClick={()=>setReading(true)}>Prefiero el modo lectura <ArrowUpRight size={18}/></button><div className="intro-bottom"><span className="small-label">MI STACK PRINCIPAL</span><div className="techline">Java <span>/</span> Spring Boot <span>/</span> AWS</div></div></aside>
<section className="console-zone" aria-label="CV interactivo"><div className="orbit-label"><span className="live-light"/> PLAYER ONE · READY TO EXPLORE</div><div className="console" id="console"><div className="console-top"><button className="power-switch" onClick={()=>{setBoot(v=>v+1);back();}} aria-label="Repetir encendido y volver al menú"><span/> POWER</button><span>JCG—2026</span></div><div className="bezel"><div className="bezel-title"><i/> DOT MATRIX WITH CAREER VISION <i/></div><span className="battery"><b/>BATTERY</span><div className="lcd"><div key={boot} className="boot-screen" aria-hidden="true"><strong>JC<span>_</span></strong><span>DEVELOPER EDITION</span><i/></div><div className="lcd-status"><button onClick={back} className="screen-home" aria-label="Volver al menú">{section===null?"JC / DEVELOPER":"‹ MENÚ"}</button><span>{section===null?"▮▮▮":sections[section].toUpperCase()}</span></div><div className="lcd-body" ref={screen} aria-label="Contenido del currículum"><div className="screen-page" key={section??"menu"}>{section===null?<><div className="menu-heading"><span className="eyebrow">CAREER CARTRIDGE / 01</span><h2>Hola, mundo<span className="blink">_</span></h2><p>Elige tu siguiente pantalla.</p></div><nav className="game-menu" aria-label="Secciones del CV">{sections.map((s,i)=><button key={s} className={selected===i?'selected':''} onMouseEnter={()=>setSelected(i)} onFocus={()=>setSelected(i)} onClick={()=>{openSection(i);}}><span>{selected===i?'▶':'·'} {s}</span><span>{visited.includes(i)?'✓':String(i+1).padStart(2,'0')}</span></button>)}</nav></>:<Content section={section}/>}</div></div>{section!==null&&<div className="reading-progress" aria-hidden="true"><i style={{width:`${progress}%`}}/></div>}<div className="lcd-footer"><span>{section===null?'↑↓ ELEGIR   A ABRIR':'↑↓ LEER  ←→ SECCIÓN'}</span><span>{section===null?'MENU':`${String(section+1).padStart(2,'0')} / 06`}</span></div></div></div>
<div className="console-brand">Javier Cano <strong>DEV BOY</strong><span>™</span></div><div className="controls"><div className="dpad" aria-label="Cruceta"><button className="up" aria-label="Arriba" onClick={()=>move(-1)}>▲</button><button className="left" aria-label="Sección anterior" onClick={()=>sideways(-1)}>◀</button><span className="pad-center"/><button className="right" aria-label="Sección siguiente" onClick={()=>sideways(1)}>▶</button><button className="down" aria-label="Abajo" onClick={()=>move(1)}>▼</button></div><div className="ab"><div><button onClick={back} aria-label="B: volver al menú"/><span>B</span></div><div><button onClick={enter} aria-label="A: abrir sección"/><span>A</span></div></div></div><div className="bottom-controls"><div className="minor"><button onClick={()=>setReading(true)} aria-label="Select: modo lectura"/><span>SELECT</span></div><div className="minor"><button onClick={()=>openSection(0)} aria-label="Start: ver perfil"/><span>START</span></div></div><div className="speaker" aria-hidden="true">{[0,1,2,3,4,5].map(n=><i key={n}/>)}</div><div className="serial">PERSONAL PORTFOLIO SYSTEM</div></div><div className="screen-caption" aria-live="polite"><span>{visited.length===sections.length?"★ Recorrido completo. ¿Escribimos el siguiente capítulo?":sectionHints[section??selected]}</span><span className="explored" aria-label={`${visited.length} de ${sections.length} secciones exploradas`}>{String(visited.length).padStart(2,"0")} / 06</span></div><div className="under-console"><span><kbd>↑</kbd><kbd>↓</kbd> navegar <kbd>↵</kbd> abrir <kbd>esc</kbd> volver</span><button onClick={()=>setSound(v=>!v)} aria-pressed={sound} aria-label={sound?'Silenciar sonido':'Activar sonido'}>{sound?<Volume2 size={17}/>:<VolumeX size={17}/>}</button><button onClick={()=>setReading(true)} aria-label="Abrir modo lectura"><Expand size={17}/></button></div></section>
<aside className="side-note"><span>{String((section??selected)+1).padStart(2,"0")} — 06</span><div className="section-dots">{sections.map((name,i)=><button key={name} className={(section??selected)===i?"active":""} aria-label={`Abrir ${name}`} title={name} onClick={()=>openSection(i)}/>)}</div><span>EXPLORA MI RECORRIDO</span></aside></main>
<footer className="footer"><span>© 2026 Javier Cano García <span className="footer-slash">/</span> Hecho con intención. Y un poco de nostalgia.</span><div><a href={links.github} target="_blank" rel="noreferrer"><Code2 size={16}/>GitHub <ArrowUpRight size={13}/></a><a href={links.linkedin} target="_blank" rel="noreferrer"><BriefcaseBusiness size={16}/>LinkedIn <ArrowUpRight size={13}/></a><a href={links.email}><Mail size={16}/>Contacto <ArrowUpRight size={13}/></a></div></footer>
<Dialog open={reading} onOpenChange={setReading}><DialogContent className="reader"><DialogTitle className="reader-title">Javier Cano García · CV</DialogTitle><DialogDescription>Backend Developer · Java & Spring Boot</DialogDescription><a className="download reader-download" href="/Javier_Cano_CV_Backend_Java_2026.pdf" download><ArrowDownToLine size={16}/> Descargar CV original</a><nav className="reader-nav" aria-label="Índice del currículum">{sections.map((s,i)=><a key={s} href={`#cv-${sectionIds[i]}`} onClick={e=>{e.preventDefault();document.getElementById(`cv-${sectionIds[i]}`)?.scrollIntoView({block:"start",behavior:"instant"});document.getElementById(`cv-${sectionIds[i]}`)?.focus({preventScroll:true});}}>{s}</a>)}</nav><div className="reader-content">{sections.map((s,i)=><section id={`cv-${sectionIds[i]}`} tabIndex={-1} key={s}><Content section={i}/></section>)}</div></DialogContent></Dialog>
</div>;
}


